// Code generated by "stringer -type GClueAccuracyLevel GClueAccuracyLevel.go"; DO NOT EDIT.

package go_geoclue2

import "strconv"

const (
	_GClueAccuracyLevel_name_0 = "NoneCountry"
	_GClueAccuracyLevel_name_1 = "CityNeighborhoodStreet"
	_GClueAccuracyLevel_name_2 = "Exact"
)

var (
	_GClueAccuracyLevel_index_0 = [...]uint8{0, 4, 11}
	_GClueAccuracyLevel_index_1 = [...]uint8{0, 4, 16, 22}
)

func (i GClueAccuracyLevel) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _GClueAccuracyLevel_name_0[_GClueAccuracyLevel_index_0[i]:_GClueAccuracyLevel_index_0[i+1]]
	case 4 <= i && i <= 6:
		i -= 4
		return _GClueAccuracyLevel_name_1[_GClueAccuracyLevel_index_1[i]:_GClueAccuracyLevel_index_1[i+1]]
	case i == 8:
		return _GClueAccuracyLevel_name_2
	default:
		return "GClueAccuracyLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
